name: hightouch_events
description: The hassle-free way to add Hightouch Events to your Flutter app.
version: 1.0.2
homepage: https://github.com/ht-sdks/events-sdk-flutter#readme
repository: https://github.com/ht-sdks/events-sdk-flutter/tree/main/packages/core#readme
issue_tracker: https://github.com/ht-sdks/events-sdk-flutter/issues

environment:
  sdk: ">=2.19.2 <4.0.0"
  flutter: ">=2.5.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_web_plugins:
    sdk: flutter
  plugin_platform_interface: ^2.0.2
  uuid: ^4.0.0
  json_annotation: ^4.8.0
  state_notifier: ^0.7.2
  http: ">=0.13.6 <2.0.0"
  logger: ^2.0.2+1
  path_provider: ^2.0.12
  flutter_fgbg: ^0.7.1
  shared_preferences: ^2.2.2
  web: ^0.5.1

dev_dependencies:
  build_runner: ^2.3.3
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  json_serializable: ^6.6.0
  pigeon: ^7.2.1
  mockito: ^5.3.2

flutter:
  plugin:
    platforms:
      android:
        package: com.hightouch.events
        pluginClass: HightouchEventsPlugin
      ios:
        pluginClass: HightouchEventsPlugin
      macos:
        pluginClass: HightouchEventsPlugin
      web:
        pluginClass: AnalyticsWeb
        fileName: analytics_web.dart
